kind: Deployment
apiVersion: apps/v1
metadata:
  name: emitter
spec:
  replicas: 64
  selector:
    matchLabels:
      name: emitter
  template:
    metadata:
      labels:
        name: emitter
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
#                  - key: "app.kubernetes.io/component"
#                    operator: In
#                    values: [ "distributor","ingester" ]
                  - key: "app"
                    operator: In
                    values: [ "loki" ]
              topologyKey: kubernetes.io/hostname
      containers:
        - name: emitter
          image: quay.io/mmaciasl/fake-flow-loki-emitter:latest
          imagePullPolicy: Always
          env:
            - name: LOKI_HOST
              value: http://loki:3100
              #value: http://loki-loki-distributed-distributor:3100
            - name: HASH_PODS_BASE
              value: 'true'
            - name: FLOWS_PER_SECOND
              value: '20000'
            - name: CONCURRENT
              value: 'false'
            - name: PODS
              value: '5'





