config:
  auth_enabled: false

  server:
    http_listen_port: 3100

  ingester:
    chunk_idle_period: 5m
    chunk_retain_period: 30s
    concurrent_flushes: 128
    max_chunk_age: 3m

  schema_config:
    configs:
      - from: 2020-05-15
        store: boltdb-shipper
        object_store: s3
        schema: v11
        index:
          prefix: index_
          period: 24h

  storage_config:
    boltdb_shipper:
      active_index_directory: /loki/index
      cache_location: /loki/index_cache
      shared_store: s3
    aws:
      s3: "s3://us-east-1/{{ .Values.bucketname }}"
      access_key_id: "{{ .Values.access_key }}"
      secret_access_key: "{{ .Values.secret_access_key }}"
      s3forcepathstyle: true
  limits_config:
    enforce_metric_name: false
    reject_old_samples: true
    reject_old_samples_max_age: 168h
    ingestion_rate_mb: 150
    max_streams_per_user: 10000

extraVolumes:
  - name: index
    emptyDir: {}
  - name: indexcache
    emptyDir: {}
extraVolumeMounts:
  - name: index
    mountPath: /loki/index
  - name: indexcache
    mountPath: /loki/index_cache


