loki:
  config: |
    auth_enabled: false

    server:
      http_listen_port: 3100

    distributor:
      ring:
        kvstore:
          store: consul
          consul:
            host: consul-consul-server:8500

    ingester:
      lifecycler:
        ring:
          kvstore:
            store: consul
            consul:
              host: consul-consul-server:8500
        final_sleep: 0s
      chunk_idle_period: 5m
      chunk_retain_period: 30s

    schema_config:
      configs:
        - from: 2020-05-15
          store: boltdb-shipper
          object_store: s3
          schema: v11
          index:
            prefix: index_
            period: 24h

    storage_config:
      boltdb_shipper:
        active_index_directory: /loki/index
        cache_location: /loki/index_cache
        shared_store: s3
      aws:
        s3: s3://us-east-1/{{ .Values.bucketname }}
        access_key_id: {{ .Values.access_key }}
        secret_access_key: {{ .Values.secret_access_key }}
        s3forcepathstyle: true
    limits_config:
      enforce_metric_name: false
      reject_old_samples: true
      reject_old_samples_max_age: 168h
ingester:
  replicas: 2
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - {key: "app.kubernetes.io/component", operator: In, values: ["ingester", "distributor","querier"]}
          topologyKey: kubernetes.io/hostname
  extraVolumes:
    - name: index
      emptyDir: {}
  extraVolumeMounts:
    - name: index
      mountPath: /loki/index

distributor:
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - {key: "app.kubernetes.io/component", operator: In, values: ["ingester","querier"]}
          topologyKey: kubernetes.io/hostname
gateway:
  enabled: false
querier:
  serviceLabels:
    testRole: querier
  affinity: |
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - {key: "app.kubernetes.io/component", operator: In, values: ["ingester","distributor"]}
          topologyKey: kubernetes.io/hostname
  extraVolumes:
    - name: index
      emptyDir: {}
    - name: indexcache
      emptyDir: {}
  extraVolumeMounts:
    - name: index
      mountPath: /loki/index
    - name: indexcache
      mountPath: /loki/index_cache